<!-- Generated by product toolbar Plugin /// Starts-->
<style>
.tinymce{
	width:500px;
	height:300px;
}
.ajaxmessage{
position:absolute;
display:none;
top:-100000;
font-family:Verdana, Arial, Helvetica, sans-serif;
-moz-border-radius:5px;
margin:0 auto;
font-size:22px;
color:#FFF;
background:#333 url(<?php echo rspro_plugin_url(); ?>/js/check.png) no-repeat 10px center;
padding:20px 20px 20px 60px;
}

</style>
<link href="<?php echo rspro_plugin_url(); ?>/css/default.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="<?php echo rspro_plugin_url(); ?>/css/colorpicker.css" type="text/css" />
<script type="text/javascript" src="<?php echo rspro_plugin_url(); ?>/js/colorpicker.js"></script>
<script type="text/javascript">
var pluginUrl='<?php echo rspro_plugin_url(); ?>/';
var stylesheetUrl='<?php bloginfo('stylesheet_url'); ?>';
jQuery(document).ready(function ($) {
	$('#fileQueue').hide();
	$('#rsporBgColor').css({width:100}).after($('<input />').css({display:'inline-block',background:$('#rsporBgColor,#product_color').val()}).attr({id:'rsporBgColorShow',size:5,type:'text'}));
	
	
	$('#rsporBgColorShow').ColorPicker({
	color: '#0000ff',
	onShow: function (colpkr) {
		$(colpkr).fadeIn(500);
		return false;
	},
	onHide: function (colpkr) {
		$(colpkr).fadeOut(500);
		return false;
	},
	onChange: function (hsb, hex, rgb) {
		$('#rsporBgColor,#product_color').val('#' + hex);
		$('#rsporBgColorShow').css({background:'#' + hex});
	}
});


	
	$('textarea.tinymce').tinymce({
		// Location of TinyMCE script
		script_url: pluginUrl + 'js/tiny_mce/tiny_mce.js',
		// General options
		theme: "advanced",
		plugins: "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
		// Theme options
		theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect",
		theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,cleanup,help,code,|,inserttime,preview",
		theme_advanced_toolbar_location: "top",
		theme_advanced_toolbar_align: "left",
		theme_advanced_statusbar_location: "bottom",
		theme_advanced_resizing: true,
		// Example content CSS (should be your site CSS)
		content_css: "css/content.css",
		// Drop lists for link/image/media/template dialogs
		template_external_list_url: "lists/template_list.js",
		external_link_list_url: "lists/link_list.js",
		external_image_list_url: "lists/image_list.js",
		media_external_list_url: "lists/media_list.js",
		// Replace values for the template plugin
		template_replace_values: {
			username: "Some User",
			staffid: "991234"
		}
	});
});
</script>

<script type="text/javascript">
jQuery(document).ready(function ($) {
	$('#rspro_country').change(function () {
		$name = $('option:selected', $(this)).text();
		$value = $('option:selected', $(this)).val();
		$id = 'country_' + $value;
		if (!$('#' + $id).html() && $value != "") {
			$('#rspro_geotargets').append($('<span></span>').append($('<a></a>').addClass('ntdelbutton').text('X')).addClass('rspro_country_btn').attr('id', $id).append('&nbsp;' + $name));
			$('#' + $id).append($('<input />').attr('name', 'rspro_geotarget[]').attr('value', $value).attr('type', 'hidden'));
		}
	});
	$('#rspro_category').change(function () {
		$name = $('option:selected', $(this)).text();
		$value = $('option:selected', $(this)).val();
		$id = 'category_' + $value;
		if (!$('#' + $id).html() && $value != "") {
			$('#rspro_categories').append($('<span></span>').append($('<a></a>').addClass('ntdelbutton').text('X')).addClass('rspro_category_btn').attr('id', $id).append('&nbsp;' + $name));
			$('#' + $id).append($('<input />').attr('name', 'rspro_categories[]').attr('value', $value).attr('type', 'hidden'));
		}
	});
	$('#rspro_geotargets span a.ntdelbutton,#rspro_categories span a.ntdelbutton').live('click', function () {
		$(this).parent().fadeOut(300, function () {
			$(this).remove();
		});
	});
});</script>
<!-- Generated by product toolbar Plugin /// Ends-->

